# Generated by Django 5.1.1 on 2024-10-06 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_enrol', models.IntegerField(unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Commitment_Role',
            fields=[
                ('commitment_role', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('experience', models.CharField(max_length=255)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branch')),
                ('skill_id', models.ManyToManyField(to='api.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128)),
                ('group_description', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ManyToManyField(related_name='member_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=128)),
                ('event_description', models.TextField()),
                ('registration_deadline', models.DateTimeField()),
                ('additional_details_link', models.URLField()),
                ('event_category_id', models.ManyToManyField(to='api.category')),
                ('visible_to_group_id', models.ManyToManyField(to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Event_Expertise',
            fields=[
                ('expertise', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('event_expertise', models.TextField()),
                ('commitment_role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commitment_role')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('person_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('team_theme_goals', models.TextField()),
                ('expectations', models.TextField()),
                ('max_members', models.PositiveSmallIntegerField()),
                ('admin_expertise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person_event_expertise')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('team_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_teams', to=settings.AUTH_USER_MODEL)),
                ('team_member_id', models.ManyToManyField(related_name='member_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joining_Request',
            fields=[
                ('request', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField()),
                ('person_expertise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person_event_expertise')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attachments_url', models.URLField()),
                ('field', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.profile')),
            ],
        ),
    ]
