# Generated by Django 5.1.1 on 2024-12-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_branch_id_alter_profile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill_id',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
    ]
