# Generated by Django 5.1.1 on 2024-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_details_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
