# Generated by Django 5.1.1 on 2024-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_additional_details_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
