# Generated by Django 5.1.1 on 2024-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
