# Generated by Django 5.1.1 on 2024-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_branch_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visible_to_group_id',
            field=models.ManyToManyField(null=True, to='api.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.TextField(null=True),
        ),
    ]
