# Generated by Django 5.1.1 on 2024-12-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_admin_id_group_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year',
        ),
    ]
