# Generated by Django 5.1.1 on 2024-12-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_branch_id_remove_profile_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
