# Generated by Django 5.1.1 on 2024-12-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
