# Generated by Django 5.1.1 on 2024-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_skill_id_profile_skills_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience', models.AutoField(primary_key=True, serialize=False)),
                ('experience_title', models.CharField(max_length=255)),
                ('experience_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='experiences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
