# Generated by Django 5.1.1 on 2024-12-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_experience_remove_profile_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experiences',
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.profile'),
            preserve_default=False,
        ),
    ]
