# Generated by Django 5.1.1 on 2024-12-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_id',
            field=models.ManyToManyField(related_name='member_groups', to='api.profile'),
        ),
    ]
