# Generated by Django 5.1.1 on 2024-12-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_group_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_theme_goals',
            new_name='team_description',
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
