# Generated by Django 5.1.1 on 2024-12-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_team_theme_goals_team_team_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joining_request',
            name='person_expertise_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='admin_expertise_id',
        ),
        migrations.AddField(
            model_name='joining_request',
            name='person_expertise',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='admin_expertise',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='commitment_role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.commitment_role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='expectations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Person_Event_Expertise',
        ),
    ]
