# Generated by Django 5.1.1 on 2024-12-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_joining_request_person_expertise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment_role',
            name='role_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='commitment_role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_teams', to='api.commitment_role'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='api.event'),
        ),
    ]
