# Generated by Django 5.1.1 on 2024-12-26 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_commitment_role_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joining_request',
            name='person_expertise',
        ),
        migrations.AddField(
            model_name='joining_request',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
