# Generated by Django 5.1.1 on 2024-12-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_request_joining_request_joining_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining_request',
            name='is_reviewed',
            field=models.BooleanField(default=0),
        ),
    ]
