# Generated by Django 5.1.1 on 2024-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments_url',
            field=models.ImageField(blank=True, null=True, upload_to='project_attachments/'),
        ),
    ]
